POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Tony Stark",
    "email": "tony@gmail.com",
    "password": "246810",
    "confPassword": "246810",
    "role": "user"
}

###
//get all users
GET http://localhost:5000/users


###
//get user by id
GET http://localhost:5000/users/26011a4c-5127-41d6-902d-6c61922dde6d

###
//update user by id
PATCH  http://localhost:5000/users/26011a4c-5127-41d6-902d-6c61922dde6d
Content-Type: application/json

{
    "name": "John Doily",
    "email": "john@gmail.com",
    "password": "234567",
    "confPassword": "234567",
    "role": "user"
}

###
//delete user by id
DELETE http://localhost:5000/users/0f2234b3-59f2-4575-89d5-6f4b92f12155

###
//login
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "admin@gmail.com",
    "password": "123456"
}

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "John@gmail.com",
    "password": "234567"
}

###
//Get session
GET http://localhost:5000/me

###
//logout
DELETE http://localhost:5000/logout

###
//get products
GET http://localhost:5000/products

###
//create product 
POST http://localhost:5000/products
Content-Type: application/json

{
    "name": "Product 4",
    "price": 11000
}

###
//get products by id
GET http://localhost:5000/products/9cba4506-faca-4fec-93fd-b4bbdfe6123c


###
//update product 
PATCH http://localhost:5000/products/9cba4506-faca-4fec-93fd-b4bbdfe6123c
Content-Type: application/json

{
    "name": "Product 2 updated",
    "price": 2000
}

###
//delete product
DELETE http://localhost:5000/products/42a9676a-b6cf-4ee0-b2a6-d781f5d9def8